#!/bin/bash
if [[ $1 == "--help" ]]; then
    echo "Usage: get_day_input year day"
    exit 0
fi
YEAR=$1
DAY=$2
SESSION=$(cat cookie.txt)
curl "https://adventofcode.com/$YEAR/day/$DAY/input" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0' -H "Referer: https://adventofcode.com/$YEAR/day/$DAY" -H "Cookie: session=$SESSION" > puzzle_input.txt
